name: Docker Test

on:
  push:
    branches:
      - rob-dev

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Build Docker Image
      run: |
        cd rfserver 
        docker build -t my_image .
      
    - name: Run Docker Container
      run: docker run --rm -d -p 53224:53224/udp --name test_container my_image

    - name: Install Python Deps
      run: pip install pytest

    - name: Run Python Tests
      run: |
        cd tools
        pytest
      
    - name: Stop and Remove Docker Container
      run: |
        docker stop test_container || true
        docker rm test_container || true

